name: the_dream_solution
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # firebase 자동 배포를 위한 라이브러리
  firebase_core: ^3.13.1

  # State Management
  get: ^4.7.2

  # Network
  dio: ^5.8.0+1

  # Storage
  flutter_secure_storage: ^9.2.4

  # Environment Variables
  envied: ^1.1.1
  envied_generator: ^1.1.1

  # Functional Programming
  dartz: ^0.10.1

  # UI Components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
